AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates an S3 bucket for source files to be uploaded to"

Resources:
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties: 
      BucketName: !Sub "data-platform-source-bucket-${AWS::Region}"
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  DataPlatformSourceBucketName:
    Export: 
      Name: "DataPlatformSourceBucketName"
    Description: "The name of the source bucket"
    Value: !Ref "Bucket"
  DataPlatformSourceBucketArn:
    Export: 
      Name: "DataPlatformSourceBucketArn"
    Description: "The ARN of the source bucket"
    Value: !GetAtt "Bucket.Arn"